apiVersion:  kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
patches:
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: staging
  - path: deploy-patch.yaml
    target:
      kind: Deployment
      name: webapp-deployment
  - path: service-patch.yaml
    target:
      kind: Service
      name: webapp-svc
