apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
  namespace: dev
  labels:
    app: webapp

spec:
  ports:
    - protocol: TCP
      port: 80
      name: http-port
      targetPort: 80
  type: NodePort
  selector:
    app: webapp
    env: dev
