apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: webapp
      env: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
        env: dev
